# Generated by Django 5.0.4 on 2024-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.IntegerField(max_length=255)),
                ('door_no', models.IntegerField(max_length=255)),
                ('new_subno', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('owner_address', models.TextField()),
                ('occupier_address', models.TextField()),
                ('floor_area', models.FloatField()),
                ('ground_area', models.FloatField()),
                ('first_floorarea', models.FloatField()),
                ('total', models.FloatField()),
                ('buldling_usage', models.TextField()),
                ('zone', models.TextField()),
                ('road_type', models.CharField(max_length=255)),
                ('road_name', models.CharField(max_length=255)),
                ('building_age', models.CharField(max_length=255)),
                ('modification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_address', models.TextField()),
                ('ph_number', models.IntegerField()),
                ('occupier_address', models.TextField()),
                ('floor_area', models.FloatField()),
                ('ground_floorarea', models.FloatField()),
                ('first_floorarea', models.FloatField()),
                ('Total', models.FloatField()),
                ('bulding_usage', models.TextField()),
                ('modification', models.CharField(max_length=255)),
            ],
        ),
    ]
