# Generated by Django 5.0.4 on 2024-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_assesment_ground_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='aadhar_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='building_age_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='building_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='building_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='currentroofdetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='exservice_men',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='nearby_roadname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='no_of_persons',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='numberoffloor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='occupier_phno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='owners_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='ownership',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='road_category',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='road_surfacetype',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='road_width',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='survey_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='swimmingpool',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='tax_exemption',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='village',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='ward_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='code',
            field=models.CharField(max_length=25),
        ),
    ]
