# Generated by Django 5.0.4 on 2024-04-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_field_aadhar_no_field_building_age_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='date',
            new_name='S_date',
        ),
    ]
