# Generated by Django 5.0.4 on 2024-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_date_field_s_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avilabe_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_wardno', models.IntegerField()),
                ('new_doorno', models.IntegerField()),
                ('new_subno', models.CharField(max_length=10)),
                ('owner_address', models.CharField(max_length=200)),
                ('floor_area', models.CharField(max_length=50)),
                ('buliding_usage', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('road_type', models.CharField(max_length=50)),
                ('road_name', models.CharField(max_length=50)),
                ('buliding_age', models.CharField(max_length=25)),
                ('roof_details', models.CharField(max_length=200)),
                ('floor_details', models.CharField(max_length=200)),
                ('Ac', models.CharField(max_length=20)),
                ('modification', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Assesment',
        ),
    ]
