# Generated by Django 5.0.4 on 2024-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_missing_details_new_doorno_missing_details_new_subno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Missing_details',
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='building_usage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='difference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='first_floor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='ground_floor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='occupier_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='owner_PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='percent_difference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avilabe_data',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avilabe_data',
            name='Ac',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='avilabe_data',
            name='modification',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
