# Generated by Django 5.0.4 on 2024-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_avilabe_data_code_avilabe_data_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='avilabe_data',
            constraint=models.UniqueConstraint(fields=('new_wardno', 'new_doorno', 'new_subno'), name='unique_warno_doorno_subno'),
        ),
    ]
